constants =
  LOAD_RENTAL_ESTIMATE: "LOAD_RENTAL_ESTIMATE"
  LOAD_RENTAL_ESTIMATE_SUCCESS: "LOAD_RENTAL_ESTIMATE_SUCCESS"
  LOAD_RENTAL_ESTIMATE_FAIL: "LOAD_RENTAL_ESTIMATE_FAIL"

module.exports = constants
